version: '2'
name: nginx
services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot:/var/www/certbot/:rw
      - letsencrypt:/etc/letsencrypt/:rw
      
  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    networks:
      - primary
    volumes:
      - nginx-config:/etc/nginx
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  

volumes:
  nginx-config:
  letsencrypt:
  certbot:

networks:
  primary:
    external: true
